name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install tree-sitter
      run: sudo make -C lib/tree-sitter/ install
    - name: make
      run: make
    - name: install script
      run: make install
